source:
  - "client/**/*"
  - "codefresh/**/*"
  - "*.go"
  - "*.mod"
  - "*.sum"

docs:
  - README.md
  - docs/**/*
  - templates/**/*
  - examples/**/*
  - tf_modules/**/*
  - CHANGELOG.md

automation:
  - scripts/**/*
  - .github/**/*
  - codefresh.yml
  - .goreleaser.yml
  - GNUmakefile
