name: "Changelog from Release"

on:
  release:
    types: [published, released]

jobs:
  update_changelog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: master
      - uses: rhysd/changelog-from-release/action@v3
        with:
          file: CHANGELOG.md
          github_token: ${{ secrets.CF_CI_BOT_PAT }}
          commit_summary_template: 'Update CHANGELOG.md for %s'
