name: "Update Terraform Provider Docs"
on:
  issue_comment:
    types: [created]
  pull_request:
    paths:
      - "**/*.go"
      - "templates/**/*"

jobs:
  tfplugindocs-generate:
    # Always run if pull_request was triggered because of paths, but also run if someone commented /docs on a PR
    if: github.event_name == 'pull_request' || (github.event.issue.pull_request && contains(github.event.comment.body, '/docs'))
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
      - name: Generate Docs
        env:
          GOPATH: "/home/runner/go"
        run: |
          export PATH=$PATH:$GOPATH
          make docs-prepare
          ls -lah $GOPATH
          tfplugindocs generate
      - name: Commit changes
        uses: EndBug/add-and-commit@v9.1.1
        with:
          pull: "--ff"
          message: "Update Terraform Provider Docs"
          add: "docs/**/*.md"
          default_author: github_actions
