name: "Pull Request"
on: pull_request

jobs:
  docs:
    name: "Ensure 'make docs' has been run"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Generate Docs
        run: |
          export PATH=$PATH:/home/runner/go/bin
          make docs-prepare
          tfplugindocs generate
      - id: docs-need-updating
        name: Validate No Changes
        run: |
          git diff --exit-code
  gofmt:
    name: "Ensure 'make fmt' has been run"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Run gofmt
        run: |
          go fmt
      - id: go-needs-formatting
        name: Validate No Changes
        run: |
          git diff --exit-code
  tasklist:
    name: "Ensure all PR tasks are completed"
    runs-on: ubuntu-latest
    steps:
      - uses: kentaro-m/task-completed-checker-action@v0.1.1
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
