name: "Validate Docs and Go Code"
on: pull_request

jobs:
  tfplugindocs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Generate Docs
        run: |
          export PATH=$PATH:/home/runner/go/bin
          make docs-prepare
          tfplugindocs generate
      - id: docs-need-updating
        name: Validate No Changes
        run: |
          git diff --exit-code
      - name: Issue Comment on PR
        if: steps.docs-need-updating.output.outcome != 'success'
        uses: thollander/actions-comment-pull-request@v2.3.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          message: |
            :warning: Terraform Provider Docs need updating!

            Run:

            ```bash
            $ make docs
            ```

            Then commit the changes.
          pr_number: ${{ github.event.pull_request.number }}
          comment_tag: docs-need-updating

  gofmt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Run gofmt
        run: |
          go fmt
      - id: go-needs-formatting
        name: Validate No Changes
        run: |
          git diff --exit-code
      - name: Issue Comment on PR
        if: steps.go-needs-formatting.output.outcome != 'success'
        uses: thollander/actions-comment-pull-request@v2.3.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          message: |
            :warning: Go code needs formatting!

            Run:

            ```bash
            $ make fmt
            ```

            Then commit the changes.
          pr_number: ${{ github.event.pull_request.number }}
          comment_tag: go-needs-formatting
